INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Schinner LLC', 766817, 'completed');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Murphy, Legros and Muller', 924140, 'on-hold');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Ruecker Inc', 695885, 'completed');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Schulist, Toy and Waters', 223964, 'completed');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Jacobs - Volkman', 288247, 'active');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Purdy - Keeling', 707771, 'completed');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'MacGyver, Terry and Yundt', 653320, 'completed');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Buckridge and Sons', 838948, 'on-hold');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Cartwright, Connelly and Quigley', 28621, 'completed');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Cassin - Mraz', 956078, 'active');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Walter - Wisoky', 698505, 'on-hold');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Nader Inc', 490594, 'active');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Rath Inc', 397543, 'completed');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Waters, Kuphal and Weissnat', 779778, 'active');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'VonRueden, Schmeler and Ankunding', 149490, 'active');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Beatty - Lowe', 255157, 'completed');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Carroll and Sons', 422525, 'active');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Paucek, Marquardt and Towne', 463407, 'on-hold');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Corkery - Greenfelder', 568503, 'active');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'O''Conner, Powlowski and Hermann', 37461, 'on-hold');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'McClure, Emard and Yundt', 934981, 'active');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Roberts Inc', 677113, 'completed');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Luettgen - Hahn', 389396, 'on-hold');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Hamill - Simonis', 171099, 'on-hold');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Hayes, Weissnat and Hammes', 380042, 'active');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Ziemann, Little and Feeney', 460857, 'completed');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Erdman, Hermiston and Shields', 864884, 'on-hold');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Wiza, Lemke and Willms', 586466, 'completed');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Rau LLC', 364982, 'on-hold');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Shanahan Inc', 408006, 'on-hold');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Corkery LLC', 676365, 'on-hold');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Lesch - Bashirian', 404409, 'on-hold');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Block, Bechtelar and Sauer', 896769, 'active');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Schmitt, Konopelski and Collier', 516485, 'on-hold');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Dickens, Senger and Considine', 625013, 'active');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Veum LLC', 869017, 'active');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Towne - Stamm', 880559, 'completed');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Corkery - Smith', 935449, 'active');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Streich - Reichel', 730918, 'on-hold');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Hahn and Sons', 324772, 'on-hold');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Goodwin - Gleichner', 826979, 'completed');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Bernhard - Kuhlman', 253562, 'completed');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Quigley and Sons', 540152, 'completed');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Skiles - Ward', 713245, 'active');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Quitzon, Heaney and Wolf', 99922, 'active');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Schowalter - Dietrich', 753010, 'active');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Reilly LLC', 916850, 'completed');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Schuppe Group', 757945, 'active');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Goyette - Altenwerth', 481392, 'on-hold');
INSERT INTO projects (tenant_id, name, budget, status) VALUES ('org_demo_123', 'Wolf - Jakubowski', 882249, 'on-hold');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Dr. Jasmine Willms PhD', 'Investor Configuration Strategist');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Sherry Doyle', 'Lead Markets Analyst');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Teri Jacobi-Sipes', 'Customer Metrics Director');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Karl Gleason', 'Product Usability Assistant');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Mitchell Connelly', 'Corporate Configuration Supervisor');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Willie Johnson', 'Future Infrastructure Facilitator');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Harry Satterfield', 'Corporate Research Executive');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Miss Cathy Bergnaum', 'Regional Functionality Engineer');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Mr. Jesus Lind', 'Human Identity Technician');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Beverly Bailey', 'National Data Orchestrator');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Tami Brekke', 'Corporate Data Agent');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Andrea Gottlieb', 'Investor Interactions Manager');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Grace Champlin', 'Customer Response Designer');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Shari Denesik', 'Product Implementation Supervisor');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Michele Ernser', 'Product Optimization Strategist');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Ms. Leah Turner', 'Investor Implementation Officer');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Cecilia Fritsch II', 'Human Factors Director');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Irvin Rohan-Okuneva', 'Product Markets Director');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Josephine Deckow', 'Direct Quality Assistant');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Leroy Willms', 'Investor Group Technician');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Traci Kuphal I', 'Lead Web Engineer');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Miss Angie Kuhlman-Hoppe', 'Senior Solutions Assistant');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Dr. Elbert Ortiz', 'Corporate Research Supervisor');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Jeffery Dooley', 'Legacy Branding Coordinator');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Ms. Norma Trantow', 'Global Paradigm Architect');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Mr. Dan Hudson', 'Principal Interactions Analyst');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Courtney Hegmann', 'Future Operations Architect');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Clay Huel-Welch', 'Product Directives Technician');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Anna Kertzmann', 'Global Accounts Supervisor');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Lori Shanahan', 'Lead Tactics Representative');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Benjamin Goldner', 'Legacy Research Engineer');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Mrs. Leigh Goldner', 'Investor Response Developer');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Fredrick Harris', 'Regional Implementation Designer');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Earnest Hermann-Bogan', 'Legacy Data Architect');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Jamie Stokes', 'District Marketing Assistant');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Tyrone Anderson', 'Senior Directives Coordinator');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Sandra Towne', 'Regional Communications Technician');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Lorena Wintheiser', 'Future Security Planner');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Joy Pollich', 'Corporate Identity Executive');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Jill Medhurst', 'Future Group Facilitator');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Roland Graham', 'Lead Configuration Consultant');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Cindy Johns', 'Forward Branding Officer');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Kay Morissette', 'International Identity Associate');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Mr. Javier Mayer', 'Product Marketing Producer');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Ms. Tara Dickinson', 'Lead Intranet Associate');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Laurie Romaguera DVM', 'Global Branding Coordinator');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Tyler Gibson', 'Forward Program Technician');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Cory Hand', 'National Assurance Administrator');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Woodrow Bechtelar', 'Chief Tactics Officer');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Kayla Leffler-Rolfson', 'District Applications Representative');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Guy Stiedemann', 'Principal Accounts Planner');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Mr. Dexter Abshire', 'Direct Accountability Producer');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Jermaine Boyle', 'Human Identity Orchestrator');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Pablo Altenwerth', 'Legacy Response Officer');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Paul Veum', 'District Security Director');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Penny Macejkovic', 'Product Research Planner');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Peggy Medhurst', 'Product Group Representative');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Mr. Darren Lesch', 'Principal Division Associate');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Jay Bernhard', 'Global Usability Orchestrator');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Johnnie Sanford', 'Investor Directives Executive');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Shelly McLaughlin', 'Investor Usability Liaison');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Violet Howe', 'Corporate Optimization Assistant');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Tomas Heathcote I', 'Principal Security Technician');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Mrs. Sheila Bednar', 'Customer Usability Liaison');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Randal Rath Sr.', 'Internal Program Coordinator');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Clark Konopelski', 'Product Operations Coordinator');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Wendell Ward Sr.', 'Lead Applications Technician');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Lila Price', 'Corporate Directives Executive');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Dianna Halvorson', 'Principal Division Consultant');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Nelson Stoltenberg-Bayer', 'Investor Implementation Engineer');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Bonnie Von Jr.', 'Central Quality Orchestrator');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Kevin Gerhold V', 'Senior Applications Assistant');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Marcus Crist Jr.', 'Principal Program Liaison');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Darren Gislason', 'Forward Identity Designer');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Dr. Kevin Romaguera', 'National Applications Analyst');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Roosevelt Bednar', 'Human Program Planner');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Olive Hermiston', 'Human Configuration Assistant');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Nadine Wehner', 'Principal Implementation Planner');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Pat Mann', 'Chief Configuration Planner');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Dexter Feest', 'Internal Brand Administrator');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Claire Mitchell', 'Principal Optimization Engineer');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Lori Schiller', 'Regional Optimization Agent');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Morris Schiller', 'Product Brand Strategist');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Jan Kuhic', 'Investor Identity Specialist');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Marc Hagenes', 'Future Interactions Executive');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Marsha Hayes', 'International Brand Consultant');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Diana Hilpert', 'Chief Optimization Administrator');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Alejandro Leffler', 'Human Tactics Producer');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Mr. Amos Kovacek-Keeling', 'National Program Agent');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Mr. Tony Walker Sr.', 'Investor Accountability Liaison');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Marie Hermann', 'Dynamic Solutions Developer');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Janie Boehm', 'Principal Solutions Consultant');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Laurie Ward DDS', 'Direct Quality Specialist');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Ms. Ora Borer', 'Regional Tactics Technician');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Allison Osinski', 'Internal Web Developer');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Miss Lauren Barrows', 'Direct Brand Architect');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Vera Robel', 'Lead Marketing Liaison');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Joanna Bosco', 'Regional Applications Engineer');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Edgar Runolfsdottir', 'Principal Accountability Administrator');
INSERT INTO employees (tenant_id, name, role) VALUES ('org_demo_123', 'Cary Reilly', 'Lead Marketing Manager');
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Modern Silk Towels', 875, 4068);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Handmade Concrete Tuna', 30, 3660);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Generic Ceramic Sausages', 118, 3349);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Gorgeous Plastic Pants', 706, 4786);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Recycled Wooden Computer', 327, 3511);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Incredible Cotton Fish', 638, 4970);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Bespoke Steel Pants', 486, 585);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Incredible Concrete Chips', 102, 2473);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Refined Plastic Keyboard', 975, 4902);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Electronic Aluminum Hat', 229, 4233);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Bespoke Bronze Table', 565, 3285);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Ergonomic Bamboo Salad', 237, 382);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Bespoke Metal Computer', 501, 1066);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Bespoke Bronze Mouse', 624, 978);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Frozen Marble Pizza', 160, 3985);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Awesome Bamboo Chips', 892, 1125);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Electronic Ceramic Cheese', 247, 1345);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Licensed Metal Keyboard', 70, 3691);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Practical Granite Mouse', 717, 4901);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Recycled Cotton Chips', 422, 3555);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Fantastic Cotton Pizza', 329, 298);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Handmade Ceramic Table', 772, 1936);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Refined Plastic Pizza', 784, 3693);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Intelligent Plastic Shoes', 576, 2806);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Generic Ceramic Hat', 537, 407);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Rustic Steel Bike', 607, 2338);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Luxurious Silk Gloves', 355, 2602);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Licensed Metal Towels', 944, 815);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Elegant Cotton Shoes', 824, 107);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Luxurious Rubber Car', 803, 4677);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Small Wooden Shirt', 32, 316);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Small Marble Chips', 851, 2530);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Luxurious Steel Computer', 325, 2620);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Rustic Marble Pizza', 656, 1059);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Ergonomic Marble Fish', 441, 2912);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Refined Wooden Soap', 810, 2402);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Refined Aluminum Tuna', 905, 1019);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Electronic Plastic Chips', 764, 220);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Handcrafted Rubber Chips', 816, 4532);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Refined Wooden Bacon', 72, 2195);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Fresh Silk Soap', 676, 4705);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Modern Silk Sausages', 927, 4311);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Fantastic Cotton Pants', 517, 1654);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Bespoke Ceramic Tuna', 595, 2460);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Soft Steel Chair', 51, 2403);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Licensed Wooden Chicken', 516, 1832);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Tasty Silk Pants', 744, 3224);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Small Granite Sausages', 701, 3283);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Elegant Plastic Sausages', 104, 2358);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Unbranded Bamboo Mouse', 524, 4882);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Tasty Rubber Sausages', 68, 2318);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Handmade Silk Table', 901, 4890);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Frozen Gold Bacon', 746, 3705);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Gorgeous Ceramic Mouse', 942, 983);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Practical Concrete Pants', 458, 3410);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Small Aluminum Ball', 890, 2222);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Recycled Aluminum Computer', 729, 1382);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Frozen Bronze Salad', 529, 4818);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Sleek Plastic Sausages', 764, 4407);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Soft Marble Pants', 153, 3531);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Incredible Granite Bacon', 214, 3640);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Unbranded Bronze Computer', 238, 2832);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Ergonomic Wooden Shirt', 127, 193);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Handmade Concrete Keyboard', 556, 976);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Luxurious Gold Soap', 276, 4562);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Oriental Silk Hat', 394, 2087);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Sleek Gold Tuna', 28, 3164);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Fresh Metal Towels', 478, 4737);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Refined Wooden Mouse', 60, 3578);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Electronic Cotton Gloves', 359, 1991);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Soft Wooden Soap', 264, 4402);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Tasty Bronze Shoes', 5, 2626);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Bespoke Bronze Tuna', 908, 311);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Elegant Metal Chips', 268, 1960);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Modern Wooden Gloves', 232, 2161);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Rustic Cotton Shoes', 67, 3530);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Fantastic Cotton Chair', 660, 4267);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Handcrafted Steel Gloves', 801, 4718);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Tasty Concrete Soap', 208, 2039);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Fresh Wooden Bacon', 503, 424);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Bespoke Cotton Shoes', 522, 2949);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Sleek Aluminum Computer', 112, 3742);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Handmade Steel Chips', 716, 1343);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Small Concrete Mouse', 104, 1991);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Generic Plastic Pants', 111, 2671);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Awesome Marble Towels', 588, 2598);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Electronic Bronze Pizza', 784, 206);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Ergonomic Steel Towels', 558, 1373);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Practical Silk Keyboard', 176, 3272);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Handcrafted Cotton Tuna', 49, 2262);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Soft Concrete Table', 492, 1356);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Recycled Wooden Bacon', 352, 3143);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Refined Plastic Gloves', 858, 3749);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Incredible Silk Bacon', 553, 2263);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Frozen Cotton Computer', 368, 1763);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Oriental Metal Ball', 245, 934);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Handcrafted Bronze Keyboard', 233, 1283);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Incredible Marble Pizza', 343, 281);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Refined Concrete Chicken', 494, 2230);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Oriental Granite Mouse', 480, 802);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Fresh Plastic Mouse', 46, 4716);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Elegant Gold Soap', 427, 855);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Licensed Steel Chips', 312, 3556);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Frozen Granite Soap', 223, 4301);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Electronic Concrete Cheese', 376, 943);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Refined Silk Keyboard', 737, 3196);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Unbranded Silk Chair', 904, 4174);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Small Marble Car', 559, 2881);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Soft Marble Keyboard', 601, 4770);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Soft Ceramic Table', 493, 2565);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Fresh Granite Shirt', 414, 3423);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Handcrafted Granite Computer', 284, 4472);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Small Aluminum Gloves', 568, 2059);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Handmade Marble Hat', 226, 3512);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Unbranded Bronze Pizza', 265, 2883);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Practical Cotton Car', 364, 80);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Handcrafted Granite Car', 653, 1935);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Tasty Silk Tuna', 443, 863);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Small Rubber Fish', 699, 4070);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Refined Bamboo Fish', 882, 719);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Sleek Bronze Shoes', 954, 1791);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Elegant Concrete Pizza', 749, 2136);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Unbranded Marble Bike', 677, 1203);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Bespoke Bamboo Towels', 597, 1480);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Practical Bronze Table', 336, 3353);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Gorgeous Marble Ball', 953, 4208);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Fantastic Aluminum Bacon', 600, 4328);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Generic Wooden Pizza', 297, 1743);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Oriental Aluminum Bike', 878, 3628);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Sleek Rubber Pizza', 830, 2245);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Refined Metal Fish', 884, 784);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Incredible Gold Fish', 533, 620);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Bespoke Silk Keyboard', 321, 2375);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Small Bamboo Pants', 329, 4253);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Electronic Aluminum Keyboard', 416, 4782);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Unbranded Rubber Shirt', 87, 219);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Frozen Aluminum Pizza', 707, 2432);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Frozen Silk Salad', 793, 707);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Gorgeous Marble Keyboard', 257, 342);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Oriental Rubber Car', 863, 4764);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Awesome Rubber Bike', 740, 4057);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Rustic Bamboo Soap', 109, 2056);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Incredible Wooden Keyboard', 542, 4178);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Handmade Plastic Pizza', 644, 1987);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Unbranded Marble Pizza', 519, 1368);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Soft Wooden Gloves', 775, 632);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Modern Silk Hat', 450, 4595);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Handcrafted Steel Table', 454, 3543);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Fresh Plastic Car', 990, 4244);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Frozen Marble Chips', 484, 4051);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Bespoke Wooden Car', 344, 690);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Sleek Wooden Table', 742, 668);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Modern Cotton Mouse', 223, 1841);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Ergonomic Granite Fish', 613, 4984);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Unbranded Silk Sausages', 20, 2575);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Ergonomic Aluminum Towels', 342, 2160);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Incredible Rubber Soap', 435, 2358);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Elegant Granite Cheese', 21, 441);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Modern Steel Sausages', 399, 2554);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Licensed Ceramic Pants', 661, 1562);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Modern Plastic Pizza', 661, 3242);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Elegant Plastic Bacon', 433, 2526);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Frozen Silk Bacon', 373, 4967);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Refined Steel Soap', 579, 3769);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Incredible Concrete Car', 433, 4785);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Sleek Cotton Shoes', 587, 4395);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Fresh Concrete Bacon', 890, 3741);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Ergonomic Wooden Sausages', 741, 1163);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Tasty Granite Bacon', 511, 3549);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Gorgeous Metal Sausages', 74, 1364);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Modern Ceramic Bike', 152, 3242);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Gorgeous Steel Gloves', 539, 3624);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Practical Granite Towels', 937, 4351);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Rustic Granite Gloves', 756, 1049);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Recycled Plastic Pants', 635, 4747);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Awesome Bronze Salad', 969, 2044);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Fantastic Granite Tuna', 305, 1615);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Handcrafted Steel Pants', 936, 3166);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Unbranded Marble Computer', 317, 2376);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Awesome Granite Gloves', 5, 4031);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Fresh Marble Chicken', 383, 2034);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Handmade Ceramic Pants', 195, 635);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Licensed Bronze Hat', 700, 3597);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Modern Rubber Computer', 489, 13);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Handmade Cotton Computer', 525, 324);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Small Granite Shoes', 854, 4094);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Unbranded Gold Chair', 991, 698);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Elegant Steel Chicken', 389, 4897);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Frozen Cotton Car', 258, 1836);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Rustic Steel Towels', 845, 3869);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Intelligent Granite Hat', 443, 4167);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Fresh Steel Mouse', 740, 1345);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Sleek Granite Cheese', 392, 871);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Intelligent Bamboo Bacon', 569, 2723);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Handcrafted Bamboo Soap', 34, 784);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Handcrafted Ceramic Gloves', 593, 3144);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Luxurious Steel Sausages', 987, 2172);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Practical Marble Computer', 404, 277);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Incredible Ceramic Gloves', 857, 1191);
INSERT INTO inventory (tenant_id, item_name, quantity, price) VALUES ('org_demo_123', 'Handmade Gold Computer', 37, 320);
